development:
  adapter: postgresql
  encoding: unicode
  database: mileage_tracker_development
  pool: 5
  username: mileage_tracker
  password: password
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: mileage_tracker_test
  pool: 5
  username: mileage_tracker
  password: password
  host: localhost

cucumber:
  <<: *test
